export const DECORATIVE_ELEMENTS = [
  { name: 'None', value: 'none' },
  { name: 'Stars', value: 'Star' },
  { name: 'Sparkles', value: 'Sparkles' },
  { name: 'Circles', value: 'Circle' },
  { name: 'Squares', value: 'Square' },
  { name: 'Hearts', value: 'Heart' },
  { name: 'Triangles', value: 'Triangle' },
  { name: 'Hexagons', value: 'Hexagon' },
  { name: 'Octagons', value: 'Octagon' },
  { name: 'Diamonds', value: 'Diamond' },
  { name: 'Waves', value: 'Waves' },
  { name: 'Bolts', value: 'Zap' },
  { name: 'Moon', value: 'Moon' },
  { name: 'Sun', value: 'Sun' },
  { name: 'Cloud', value: 'Cloud' },
  { name: 'Ghost', value: 'Ghost' },
  { name: 'Coffee', value: 'Coffee' },
  { name: 'Music', value: 'Music' },
  { name: 'Trophy', value: 'Trophy' },
  { name: 'Target', value: 'Target' },
  { name: 'Flame', value: 'Flame' },
  { name: 'Leaf', value: 'Leaf' },
  { name: 'Wind', value: 'Wind' },
  { name: 'Snowflake', value: 'Snowflake' },
  { name: 'Anchor', value: 'Anchor' },
  { name: 'Award', value: 'Award' },
  { name: 'Bell', value: 'Bell' },
  { name: 'Bird', value: 'Bird' },
  { name: 'Bomb', value: 'Bomb' },
  { name: 'Bot', value: 'Bot' },
  { name: 'Bug', value: 'Bug' },
  { name: 'Cake', value: 'Cake' },
  { name: 'Camera', value: 'Camera' },
  { name: 'Cat', value: 'Cat' },
  { name: 'Cherry', value: 'Cherry' },
  { name: 'Citrus', value: 'Citrus' },
  { name: 'Coins', value: 'Coins' },
  { name: 'Cookie', value: 'Cookie' },
  { name: 'Crown', value: 'Crown' },
  { name: 'Dog', value: 'Dog' },
  { name: 'Droplet', value: 'Droplet' },
  { name: 'Dumbbell', value: 'Dumbbell' },
  { name: 'Eye', value: 'Eye' },
  { name: 'Feather', value: 'Feather' },
  { name: 'Fish', value: 'Fish' },
  { name: 'Flag', value: 'Flag' },
  { name: 'Flower', value: 'Flower' },
  { name: 'Gamepad', value: 'Gamepad2' },
  { name: 'Gem', value: 'Gem' },
  { name: 'Gift', value: 'Gift' },
  { name: 'Graduation', value: 'GraduationCap' },
  { name: 'Hammer', value: 'Hammer' },
  { name: 'Metal', value: 'HandMetal' },
  { name: 'Headphones', value: 'Headphones' },
  { name: 'Ice Cream', value: 'IceCream' },
  { name: 'Infinity', value: 'Infinity' },
  { name: 'Key', value: 'Key' },
  { name: 'Lamp', value: 'Lamp' },
  { name: 'Library', value: 'Library' },
  { name: 'Life Buoy', value: 'LifeBuoy' },
  { name: 'Lightbulb', value: 'Lightbulb' },
  { name: 'Magnet', value: 'Magnet' },
  { name: 'Map', value: 'Map' },
  { name: 'Martini', value: 'Martini' },
  { name: 'Medal', value: 'Medal' },
  { name: 'Megaphone', value: 'Megaphone' },
  { name: 'Mic', value: 'Mic' },
  { name: 'Mountain', value: 'Mountain' },
  { name: 'Mouse', value: 'Mouse' },
  { name: 'Navigation', value: 'Navigation' },
  { name: 'Package', value: 'Package' },
  { name: 'Paint Bucket', value: 'PaintBucket' },
  { name: 'Paintbrush', value: 'Paintbrush' },
  { name: 'Palm Tree', value: 'Palmtree' },
  { name: 'Paperclip', value: 'Paperclip' },
  { name: 'Party Popper', value: 'PartyPopper' },
  { name: 'Piggy Bank', value: 'PiggyBank' },
  { name: 'Pizza', value: 'Pizza' },
  { name: 'Plane', value: 'Plane' },
  { name: 'Puzzle', value: 'Puzzle' },
  { name: 'Rocket', value: 'Rocket' },
  { name: 'Sailboat', value: 'Sailboat' },
  { name: 'Skull', value: 'Skull' },
  { name: 'Smile', value: 'Smile' },
  { name: 'Sprout', value: 'Sprout' },
  { name: 'Sticker', value: 'Sticker' },
  { name: 'Sword', value: 'Sword' },
  { name: 'Tent', value: 'Tent' },
  { name: 'Tornado', value: 'Tornado' },
  { name: 'Toy Brick', value: 'ToyBrick' },
  { name: 'Truck', value: 'Truck' },
  { name: 'Umbrella', value: 'Umbrella' },
  { name: 'Wand', value: 'Wand2' },
  { name: 'Wine', value: 'Wine' },
  { name: 'Globe', value: 'Globe' },
  { name: 'Laptop', value: 'Laptop' },
  { name: 'Microscope', value: 'Microscope' },
  { name: 'Newspaper', value: 'Newspaper' },
  { name: 'Pencil', value: 'Pencil' },
  { name: 'Phone', value: 'Phone' },
  { name: 'Pie Chart', value: 'PieChart' },
  { name: 'Pill', value: 'Pill' },
  { name: 'Play', value: 'Play' },
  { name: 'Plug', value: 'Plug' },
  { name: 'Pocket', value: 'Pocket' },
  { name: 'Podcast', value: 'Podcast' },
  { name: 'Power', value: 'Power' },
  { name: 'Printer', value: 'Printer' },
  { name: 'Qr Code', value: 'QrCode' },
  { name: 'Quote', value: 'Quote' },
  { name: 'Radiation', value: 'Radiation' },
  { name: 'Radio', value: 'Radio' },
  { name: 'Rat', value: 'Rat' },
  { name: 'Receipt', value: 'Receipt' },
  { name: 'Recycle', value: 'Recycle' },
  { name: 'Rss', value: 'Rss' },
  { name: 'Ruler', value: 'Ruler' },
  { name: 'Save', value: 'Save' },
  { name: 'Scale', value: 'Scale' },
  { name: 'Scan', value: 'Scan' },
  { name: 'Scissors', value: 'Scissors' },
  { name: 'Scroll', value: 'Scroll' },
  { name: 'Search', value: 'Search' },
  { name: 'Send', value: 'Send' },
  { name: 'Server', value: 'Server' },
  { name: 'Settings', value: 'Settings' },
  { name: 'Shield', value: 'Shield' },
  { name: 'Shirt', value: 'Shirt' },
  { name: 'Shopping Bag', value: 'ShoppingBag' },
  { name: 'Shopping Cart', value: 'ShoppingCart' },
  { name: 'Shovel', value: 'Shovel' },
  { name: 'Shuffle', value: 'Shuffle' },
  { name: 'Sidebar', value: 'Sidebar' },
  { name: 'Sigma', value: 'Sigma' },
  { name: 'Signal', value: 'Signal' },
  { name: 'Siren', value: 'Siren' },
  { name: 'Slack', value: 'Slack' },
  { name: 'Slash', value: 'Slash' },
  { name: 'Slice', value: 'Slice' },
  { name: 'Sliders', value: 'Sliders' },
  { name: 'Smartphone', value: 'Smartphone' },
  { name: 'Sofa', value: 'Sofa' },
  { name: 'Soup', value: 'Soup' },
  { name: 'Speaker', value: 'Speaker' },
  { name: 'Stamp', value: 'Stamp' },
  { name: 'Stethoscope', value: 'Stethoscope' },
  { name: 'Sticky Note', value: 'StickyNote' },
  { name: 'Sunrise', value: 'Sunrise' },
  { name: 'Sunset', value: 'Sunset' },
  { name: 'Swords', value: 'Swords' },
  { name: 'Syringe', value: 'Syringe' },
  { name: 'Table', value: 'Table' },
  { name: 'Tablet', value: 'Tablet' },
  { name: 'Tag', value: 'Tag' },
  { name: 'Terminal', value: 'Terminal' },
  { name: 'Thermometer', value: 'Thermometer' },
  { name: 'Thumbs Down', value: 'ThumbsDown' },
  { name: 'Thumbs Up', value: 'ThumbsUp' },
  { name: 'Ticket', value: 'Ticket' },
  { name: 'Timer', value: 'Timer' },
  { name: 'Train', value: 'Train' },
  { name: 'Trash', value: 'Trash2' },
  { name: 'Tree Pine', value: 'TreePine' },
  { name: 'Trees', value: 'Trees' },
  { name: 'Tv', value: 'Tv' },
  { name: 'Twitch', value: 'Twitch' },
  { name: 'Twitter', value: 'Twitter' },
  { name: 'User', value: 'User' },
  { name: 'Users', value: 'Users' },
  { name: 'Utensils', value: 'Utensils' },
  { name: 'Variable', value: 'Variable' },
  { name: 'Video', value: 'Video' },
  { name: 'Volume', value: 'Volume2' },
  { name: 'Wallet', value: 'Wallet' },
  { name: 'Watch', value: 'Watch' },
  { name: 'Webcam', value: 'Webcam' },
  { name: 'Webhook', value: 'Webhook' },
  { name: 'Weight', value: 'Weight' },
  { name: 'Wheat', value: 'Wheat' },
  { name: 'Wifi', value: 'Wifi' },
  { name: 'Workflow', value: 'Workflow' },
  { name: 'Youtube', value: 'Youtube' },
  { name: 'Infinity', value: 'Infinity' },
  { name: 'Languages', value: 'Languages' },
  { name: 'Life Buoy', value: 'LifeBuoy' },
  { name: 'Lightbulb', value: 'Lightbulb' },
  { name: 'Magnet', value: 'Magnet' },
  { name: 'Mail', value: 'Mail' },
  { name: 'Martini', value: 'Martini' },
  { name: 'Medal', value: 'Medal' },
  { name: 'Megaphone', value: 'Megaphone' },
  { name: 'Mic', value: 'Mic' },
  { name: 'Mountain', value: 'Mountain' },
  { name: 'Mouse', value: 'Mouse' },
  { name: 'Navigation', value: 'Navigation' },
  { name: 'Package', value: 'Package' },
  { name: 'Paint Bucket', value: 'PaintBucket' },
  { name: 'Paintbrush', value: 'Paintbrush' },
  { name: 'Palm Tree', value: 'Palmtree' },
  { name: 'Paperclip', value: 'Paperclip' },
  { name: 'Party Popper', value: 'PartyPopper' },
  { name: 'Piggy Bank', value: 'PiggyBank' },
  { name: 'Pizza', value: 'Pizza' },
  { name: 'Plane', value: 'Plane' },
  { name: 'Puzzle', value: 'Puzzle' },
  { name: 'Rocket', value: 'Rocket' },
  { name: 'Sailboat', value: 'Sailboat' },
  { name: 'Skull', value: 'Skull' },
  { name: 'Smile', value: 'Smile' },
  { name: 'Sprout', value: 'Sprout' },
  { name: 'Sticker', value: 'Sticker' },
  { name: 'Sword', value: 'Sword' },
  { name: 'Tent', value: 'Tent' },
  { name: 'Tornado', value: 'Tornado' },
  { name: 'Toy Brick', value: 'ToyBrick' },
  { name: 'Truck', value: 'Truck' },
  { name: 'Umbrella', value: 'Umbrella' },
  { name: 'Wand', value: 'Wand2' },
  { name: 'Wine', value: 'Wine' },
];

export const FONTS = [
  { name: 'Inter (Sans)', value: 'font-sans' },
  { name: 'Playfair Display (Serif)', value: 'font-serif' },
  { name: 'JetBrains Mono (Mono)', value: 'font-mono' },
  { name: 'Space Grotesk', value: 'font-space' },
  { name: 'Outfit', value: 'font-outfit' },
  { name: 'Cormorant Garamond', value: 'font-cormorant' },
  { name: 'Anton', value: 'font-anton' },
  { name: 'Lobster', value: 'font-lobster' },
  { name: 'Pacifico', value: 'font-pacifico' },
  { name: 'Display Bold', value: 'font-sans font-black uppercase italic' },
];

export const THEMES = [
  { name: 'Minimal', bg: '#ffffff', text: '#171717', border: '#e5e5e5', gradient: null },
  { name: 'Dark Mode', bg: '#171717', text: '#ffffff', border: '#262626', gradient: null },
  { name: 'Royal', bg: '#1e1b4b', text: '#e0e7ff', border: '#312e81', gradient: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)' },
  { name: 'Forest', bg: '#064e3b', text: '#ecfdf5', border: '#065f46', gradient: 'linear-gradient(135deg, #064e3b 0%, #065f46 100%)' },
  { name: 'Sunset', bg: '#7c2d12', text: '#fff7ed', border: '#9a3412', gradient: 'linear-gradient(135deg, #7c2d12 0%, #ea580c 100%)' },
  { name: 'Lavender', bg: '#4c1d95', text: '#f5f3ff', border: '#5b21b6', gradient: 'linear-gradient(135deg, #4c1d95 0%, #7c3aed 100%)' },
  { name: 'Ocean', bg: '#0c4a6e', text: '#f0f9ff', border: '#075985', gradient: 'linear-gradient(135deg, #0c4a6e 0%, #0284c7 100%)' },
  { name: 'Crimson', bg: '#ef4444', text: '#ffffff', border: '#dc2626', gradient: null },
  { name: 'Gold', bg: '#d4af37', text: '#ffffff', border: '#b8860b', gradient: null },
  { name: 'Titan', bg: '#8e8e93', text: '#ffffff', border: '#636366', gradient: null },
  { name: 'Blush', bg: '#f4c2c2', text: '#171717', border: '#e5b0b0', gradient: null },
  { name: 'Sky Blue', bg: '#e0f2fe', text: '#0369a1', border: '#bae6fd', gradient: null },
];

export const GRADIENTS = [
  { name: 'Indigo', value: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)' },
  { name: 'Rose', value: 'linear-gradient(135deg, #f43f5e 0%, #fb7185 100%)' },
  { name: 'Emerald', value: 'linear-gradient(135deg, #10b981 0%, #34d399 100%)' },
  { name: 'Amber', value: 'linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%)' },
  { name: 'Sky', value: 'linear-gradient(135deg, #0ea5e9 0%, #38bdf8 100%)' },
  { name: 'Violet', value: 'linear-gradient(135deg, #8b5cf6 0%, #a78bfa 100%)' },
  { name: 'Fuchsia', value: 'linear-gradient(135deg, #d946ef 0%, #e879f9 100%)' },
  { name: 'Slate', value: 'linear-gradient(135deg, #475569 0%, #64748b 100%)' },
];

export const TEXTURES = [
  { name: 'None', value: 'none' },
  { 
    name: 'Paper', 
    value: 'paper',
    svg: `data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E`
  },
  { 
    name: 'Dirty', 
    value: 'dirty',
    svg: `data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.05' numOctaves='2' stitchTiles='stitch'/%3E%3CfeColorMatrix type='saturate' values='0'/%3E%3CfeComponentTransfer%3E%3CfeFuncR type='discrete' tableValues='0 0.5 1'/%3E%3C/feComponentTransfer%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E`
  },
  { 
    name: 'Scratch', 
    value: 'scratch',
    svg: `data:image/svg+xml,%3Csvg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.5'/%3E%3Cline x1='0' y1='0' x2='100' y2='100' stroke='black' stroke-width='0.5' opacity='0.2'/%3E%3Cline x1='100' y1='0' x2='0' y2='100' stroke='black' stroke-width='0.5' opacity='0.1'/%3E%3C/svg%3E`
  },
  { 
    name: 'Stencil', 
    value: 'stencil',
    svg: `data:image/svg+xml,%3Csvg viewBox='0 0 20 20' xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle cx='4' cy='4' r='2' fill='black' opacity='0.2'/%3E%3C/svg%3E`
  },
  {
    name: 'Fiber',
    value: 'fiber',
    svg: `data:image/svg+xml,%3Csvg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='f'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.01 0.5' numOctaves='2'/%3E%3C/filter%3E%3Crect width='100' height='100' filter='url(%23f)' opacity='0.3'/%3E%3C/svg%3E`
  },
  {
    name: 'Noise',
    value: 'noise',
    svg: `data:image/svg+xml,%3Csvg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100' height='100' filter='url(%23n)' opacity='0.4'/%3E%3C/svg%3E`
  },
  {
    name: 'Dots',
    value: 'dots',
    svg: `data:image/svg+xml,%3Csvg width='10' height='10' viewBox='0 0 10 10' xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle cx='1' cy='1' r='0.5' fill='black' opacity='0.2'/%3E%3C/svg%3E`
  },
  {
    name: 'Lines',
    value: 'lines',
    svg: `data:image/svg+xml,%3Csvg width='10' height='10' viewBox='0 0 10 10' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M0 0 L10 10' stroke='black' stroke-width='0.5' opacity='0.1'/%3E%3C/svg%3E`
  },
  {
    name: 'Carbon',
    value: 'carbon',
    svg: `data:image/svg+xml,%3Csvg width='6' height='6' viewBox='0 0 6 6' xmlns='http://www.w3.org/2000/svg'%3E%3Crect width='3' height='3' fill='black' opacity='0.1'/%3E%3Crect x='3' y='3' width='3' height='3' fill='black' opacity='0.1'/%3E%3C/svg%3E`
  }
];
